[package]
name = "linkstore"
version = "0.1.0"
edition = "2021"
authors = ["William Venner <william@venner.io>"]

[lib]
crate-type = ["cdylib", "staticlib"]

[[bin]]
name = "sneed"
path = "src/lib.rs"

[dependencies]
goblin = "0"
thiserror = "1"
rustc-demangle = "0"
ouroboros = "0"