name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Clippy
      run: cargo clippy -- -D warnings

  format:
    needs: clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check formatting
      run: cargo fmt --all -- --check

  test_linux:
    needs: format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Add targets
      run: rustup target add x86_64-unknown-linux-gnu i686-unknown-linux-gnu
    - name: Run tests (32-bit)
      run: cargo test --target i686-unknown-linux-gnu -- --nocapture
    - name: Run tests (64-bit)
      run: cargo test --target x86_64-unknown-linux-gnu -- --nocapture

  test_windows:
    needs: format
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Add targets
      run: rustup target add x86_64-pc-windows-msvc i686-pc-windows-msvc
    - name: Run tests (32-bit)
      run: cargo test --target i686-pc-windows-msvc -- --nocapture
    - name: Run tests (64-bit)
      run: cargo test --target x86_64-pc-windows-msvc -- --nocapture

  test_macos:
    needs: format
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Add targets
      run: rustup target add x86_64-apple-darwin i686-apple-darwin
    - name: Run tests (32-bit)
      run: cargo test --target i686-apple-darwin -- --nocapture
    - name: Run tests (64-bit)
      run: cargo test --target x86_64-apple-darwin -- --nocapture
